name: news_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.5
  dartz: ^0.10.1
  dio: ^5.1.2
  easy_debounce: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_getit: ^1.2.1
  freezed_annotation: ^2.2.0
  get_it: ^7.6.0
  injectable: ^2.1.1
  intl: ^0.18.1
  json_annotation: ^4.8.1
  stylish_bottom_bar: ^1.0.1

dev_dependencies:
  build_runner: ^2.4.4
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.4
  injectable_generator: ^2.1.5
  json_serializable: ^6.7.0

flutter:
  uses-material-design: true
